### ISSUE TITLE
When I create an account instance its values are not populated

### ISSUE THREAD

**Issue by nelix** [saucelabs/sauce_whisk#1]
(ENV is setup correct, confirmed by SauceWhisk.password and by using them aganst the rest api)

SauceWhisk::Accounts.fetch
# <SauceWhisk::Account:0x007f88cd09ca60

 @access_key=nil,
 @mac_concurrency=5,
 @minutes=nil,
 @total_concurrency=5,
 @username=nil>

**Comment by bootstraponline** [comment]
I think it's safe to close this issue?

**Comment by DylanLacey** [comment]
Closing due to age.
