### ISSUE TITLE
Jobs.fetch is returning a 400 Bad request, sometimes

### ISSUE THREAD

**Issue by prolificcoder** [saucelabs/sauce_whisk#10]
SauceWhisk::Jobs.fetch job_id

is returning this
RestClient::BadRequest: 400 Bad Request
from /Users/malugus/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'

This works after a bit, if Sauce API is not reliable you should add an implicit retry loop.

**Comment by DylanLacey** [comment]
Closing due to age.
