### ISSUE TITLE
0.18 release missing from github releases page?

### ISSUE THREAD

**Issue by bootstraponline** [saucelabs/sauce_whisk#44]
https://github.com/saucelabs/sauce_whisk/releases shows 0.0.17 as the latest release although rubygems shows [0.0.18](https://rubygems.org/gems/sauce_whisk). Is there a reason the latest release wasn't tagged on github?

**Comment by DylanLacey** [comment]
Not sure.  I wonder if something went wrong during the release process.  Shrug.  I'll keep an eye out during subsequent releases.

**Comment by bootstraponline** [comment]
There's no git tag for v0.0.18 which is what GitHub uses to auto populate releases.
