### ISSUE TITLE
Unable to activate sauce_whisk-0.0.21, because json-2.0.3 conflicts with json (~> 1.8.1)

### ISSUE THREAD

**Issue by djangofan** [saucelabs/sauce_whisk#55]
How do I resolve this error?

Unable to activate sauce_whisk-0.0.21, because json-2.0.3 conflicts with json (~> 1.8.1)

**Comment by titusfortner** [comment]
I would think `bundle install` would try to grab the required version. Try:
```
gem uninstall json
gem install json -v 1.8.1
```

The `sauce_whisk.gemspec` file is specifying that particular version, though we can probably update it if it continues to cause a problem.

**Comment by djangofan** [comment]
I got it working after I started using a Gemfile  .    I'm on Windows with 64-bit Ruby 2.3.x .   My gems folder contains  json-1.8.1  and json-1.8.6  .   I'm not sure what I did to end up with that but I definitely manually uninstalled json 2.0.3 .   When I ran  "gem update" I think it re-installed json 2.0.3 without asking me.
