### ISSUE TITLE
missing option to communicate with eu-central-1

### ISSUE THREAD

**Issue by johannes112** [saucelabs/sauce_whisk#62]
i set the status (change_status) of my tests in saucelabs. With the new datacenter (eu-central-1) the url of the saucelabs rest api is changed to 'https://eu-central-1.saucelabs.com/rest' and this gem isn't working for me. How can I set the url manually?

**Comment by DylanLacey** [comment]
Closed in release `0.2.0`.

**Comment by DylanLacey** [comment]
If you set the `SAUCE_DATA_CENTER` option, or `SauceWhisk.data_center` to `:EU_VDC`, you should able to access the EUDC.
